version: '3.8'

services:
  couchdb:
    image: couchdb:latest
    restart: unless-stopped
    ports:
      - '5984:5984'
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
      COUCHDB_DATABASES: mydatabase
